#开发环境配置

#配置端口
server:
  port: 5617
  tomcat:
    max-http-form-post-size: 30MB
    basedir: /home/xiaoxuan/web-jar/tomcat_temp

#mysql数据库配置
spring:
  datasource:
    url: jdbc:mysql://139.159.250.100:3306/TPK
    username: xiaoxuan
    password: Lin6280178
  #修改这个属性
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #spring直属servlet属性
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB
      #设定默认上传路径
      location: /home/xiaoxuan/web-jar/tomcat_temp/upload

#告诉mybatis mapper的xml位置在哪
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-handlers-package: com.minxuan.sms.handler

#log4j2配置文件导入
logging:
  config: classpath:log4j2-dev.xml
  file:
    path: /home/xiaoxuan/web-jar/tomcat_temp/logs

#文件保存位置
paths:
  excels: /home/xiaoxuan/web-jar/tomcat_temp/upload

TPK:
  adultLimit: 0
  portURL: http://139.159.250.100:8081
  #权限设置
  authority:
    #业务员所在组，不匹配的会不允许登录
    EmpGroup: 2
  #容器设置
  online-container:
    #容器容量
    capacity: 4
